### ISSUE TITLE
Snow migration checklist

### ISSUE THREAD

**Issue by ruby0x1** [underscorediscovery/luxe#108]
- [x] Physics - check timing rates when using fixed_rate matched with entity.fixed_rate
- [x] Gamepads - check number of events per frame, and allow immediate style query
- [x] Utils - make maths more consistent against the rest and inline etc
- [x] Utils - remove custom base64 implementation in favor of haxe one
